/*
Auto-generated by C4D to R3F Converter
Model: balloon.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial } from '@/scene/SceneComponents'
import type { MaterialColorIndex } from '@/settings/GameSettings'
import modelUrl from './balloon.glb?url'

type MaterialColorSlot = 'materialColor0'
type MaterialHiddenSlot = 'materialHidden0'

type BalloonProps = ThreeElements['group'] & {
  materialColor0?: MaterialColorIndex
  materialHidden0?: boolean
}

export function Balloon({ materialColor0 = 3, materialHidden0 = false, ...props }: BalloonProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }

  const materialColors: Record<MaterialColorSlot, MaterialColorIndex> = {
    materialColor0,
  }

  const materialHiddens: Record<MaterialHiddenSlot, boolean> = {
    materialHidden0,
  }

  return (
    <group {...props} dispose={null}>
      <group name={""}>
        <C4DMesh name={nodes['Sphere_color3_singleTone'].name} geometry={nodes['Sphere_color3_singleTone'].geometry} castShadow receiveShadow visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} singleTone />
        </C4DMesh>
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)