/*
Auto-generated by C4D to R3F Converter
Model: bridge.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { ConvexHullCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial, GameRigidBody } from '@/scene/SceneComponents'
import type { GamePhysicsBodyType } from '@/scene/SceneComponents'
import type { MaterialColorIndex } from '@/settings/GameSettings'
import modelUrl from './bridge.glb?url'

type MaterialColorSlot = 'materialColor0'
type MaterialHiddenSlot = 'materialHidden0'
type GeneratedRigidBodySettings = {
  type: GamePhysicsBodyType
  mass?: number
  friction?: number
  lockRotations?: boolean
  sensor?: boolean
  contagionCarrier?: boolean
  contagionInfectable?: boolean
}
type RigidBodySlot = 'rigidBodyOne'

type BridgeProps = ThreeElements['group'] & {
  materialColor0?: MaterialColorIndex
  materialHidden0?: boolean
  entityId?: string
  contagionCarrier?: boolean
  contagionInfectable?: boolean
  contagionColor?: MaterialColorIndex
  rigidBodyOne?: Partial<GeneratedRigidBodySettings>
}

export function Bridge({ materialColor0 = 1, materialHidden0 = false, entityId, contagionCarrier, contagionInfectable, contagionColor, rigidBodyOne, ...props }: BridgeProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }

  const materialColors: Record<MaterialColorSlot, MaterialColorIndex> = {
    materialColor0,
  }

  const materialHiddens: Record<MaterialHiddenSlot, boolean> = {
    materialHidden0,
  }

  const rigidBodies: Record<RigidBodySlot, GeneratedRigidBodySettings> = {
    rigidBodyOne: {
      ...{ type: 'dynamic' },
      ...(rigidBodyOne ?? {}),
      ...(contagionCarrier !== undefined ? { contagionCarrier } : {}),
      ...(contagionInfectable !== undefined ? { contagionInfectable } : {}),
    },
  }

  const getRigidBodyProps = (slot: RigidBodySlot): GeneratedRigidBodySettings => {
    const body = rigidBodies[slot]
    return {
      type: body.type,
      ...(body.mass !== undefined ? { mass: body.mass } : {}),
      ...(body.friction !== undefined ? { friction: body.friction } : {}),
      ...(body.lockRotations ? { lockRotations: true } : {}),
      ...(body.sensor ? { sensor: true } : {}),
      contagionCarrier: body.contagionCarrier === true,
      contagionInfectable: body.contagionInfectable !== false,
    }
  }
  const resolvedContagionColor = contagionColor ?? materialColors.materialColor0

  return (
    <group {...props} dispose={null}>
      <group name={""}>
        <GameRigidBody {...getRigidBodyProps('rigidBodyOne')} colliders={false}
          contagion={{
            entityId,
            carrier: getRigidBodyProps('rigidBodyOne').contagionCarrier,
            infectable: getRigidBodyProps('rigidBodyOne').contagionInfectable,
            colorIndex: resolvedContagionColor,
          }}
        >
          <ConvexHullCollider args={[nodes['bridge_color1_dynamic_collider'].geometry.attributes.position.array]} />
          <C4DMesh name={nodes['bridge_color1_dynamic_collider'].name} geometry={nodes['bridge_color1_dynamic_collider'].geometry} castShadow receiveShadow visible={!materialHiddens.materialHidden0}>
            <C4DMaterial color={materialColors.materialColor0} />
          </C4DMesh>
        </GameRigidBody>
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)