/*
Auto-generated by C4D to R3F Converter
Model: laddertest.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial } from '../../SceneComponents'
import type { PaletteName } from '../../GameSettings'
import modelUrl from './laddertest.glb?url'

type LaddertestProps = ThreeElements['group'] & {
  animation?: string | null
  fadeDuration?: number
}

export function Laddertest(props: LaddertestProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }
  const colors: Record<string, PaletteName> = {
    default: 'default',
    one: 'one',
  }

  return (
    <group {...props} dispose={null}>
      <RigidBody type="dynamic" colliders={false}>
        <CuboidCollider args={[0.075, 0.345, 0.015]} position={[0, 0.345, 0]} />
        <C4DMesh name={nodes['HORIZONTALS'].name} geometry={nodes['HORIZONTALS'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.one} />
        </C4DMesh>
      </RigidBody>
    </group>
  )
}

useGLTF.preload(modelUrl)