/*
Auto-generated by C4D to R3F Converter
Model: stair.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, ConvexHullCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial } from '../../SceneComponents'
import type { PaletteName } from '../../GameSettings'
import modelUrl from './stair.glb?url'

type StairProps = ThreeElements['group'] & {
  animation?: string | null
  fadeDuration?: number
}

export function Stair(props: StairProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }
  const colors: Record<string, PaletteName> = {
    default: 'default',
    three: 'three',
  }

  return (
    <group {...props} dispose={null}>
      <RigidBody type="dynamic" colliders={false}>
        <ConvexHullCollider args={[nodes['STAIRS_collider'].geometry.attributes.position.array]} />
        <C4DMesh name={nodes['STAIRS'].name} geometry={nodes['STAIRS'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.three} />
        </C4DMesh>
        <C4DMesh name={nodes['STAIRS_top'].name} geometry={nodes['STAIRS_top'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.three} />
        </C4DMesh>
      </RigidBody>
    </group>
  )
}

useGLTF.preload(modelUrl)