/*
Auto-generated by C4D to R3F Converter
Model: stair.glb
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { ConvexHullCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial, GameRigidBody } from '@/scene/SceneComponents'
import type { GamePhysicsBodyType } from '@/scene/SceneComponents'
import type { MaterialColorIndex } from '@/settings/GameSettings'
import { useContagionColorOverride } from '@/gameplay/gameplayStore'
import type { ContagionProps } from '@/gameplay/contagionProps'
import modelUrl from './stair.glb?url'

type GeneratedRigidBodySettings = {
  type: GamePhysicsBodyType
  mass?: number
  friction?: number
  lockRotations?: boolean
  sensor?: boolean
}

type Simplify<T> = { [K in keyof T]: T[K] } & {}

export type StairProps = Simplify<ThreeElements['group'] & ContagionProps & {
  materialColor0?: MaterialColorIndex
  rigidBodyOne?: Partial<GeneratedRigidBodySettings>
}>

export function Stair({
  materialColor0 = 2,
  entityId,
  contagionCarrier = false,
  contagionInfectable = true,
  contagionColor,
  rigidBodyOne,
  ...props
}: StairProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }
  const contagionColorOverride = useContagionColorOverride(entityId)
  const resolvedMaterialColor0 = contagionColorOverride ?? materialColor0
  const materialColors: Record<'materialColor0', MaterialColorIndex> = {
    materialColor0: resolvedMaterialColor0,
  }

  const rigidBodies: Record<'rigidBodyOne', GeneratedRigidBodySettings> = {
    rigidBodyOne: { type: 'dynamic', ...(rigidBodyOne ?? {}) },
  }

  const getRigidBodyProps = (slot: 'rigidBodyOne'): GeneratedRigidBodySettings => {
    const body = rigidBodies[slot]
    return {
      type: body.type,
      ...(body.mass !== undefined ? { mass: body.mass } : {}),
      ...(body.friction !== undefined ? { friction: body.friction } : {}),
      ...(body.lockRotations ? { lockRotations: true } : {}),
      ...(body.sensor ? { sensor: true } : {}),
    }
  }

  return (
    <group {...props} dispose={null}>
      <GameRigidBody
        {...getRigidBodyProps('rigidBodyOne')}
        colliders={false}
        contagion={{
          entityId,
          carrier: contagionCarrier,
          infectable: contagionInfectable,
          colorIndex: contagionColor ?? resolvedMaterialColor0,
        }}
      >
        <ConvexHullCollider args={[nodes['STAIRS_collider'].geometry.attributes.position.array]} />
        <C4DMesh name={nodes['STAIRS'].name} geometry={nodes['STAIRS'].geometry} castShadow receiveShadow>
          <C4DMaterial color={materialColors.materialColor0} />
        </C4DMesh>
        <C4DMesh name={nodes['STAIRS_top'].name} geometry={nodes['STAIRS_top'].geometry} castShadow receiveShadow>
          <C4DMaterial color={materialColors.materialColor0} />
        </C4DMesh>
      </GameRigidBody>
    </group>
  )
}

useGLTF.preload(modelUrl)
