/*
Auto-generated by C4D to R3F Converter
Model: VaultStairs.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, ConvexHullCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial } from '../../SceneComponents'
import type { PaletteName } from '../../GameSettings'
import modelUrl from './VaultStairs.glb?url'

type VaultStairsProps = ThreeElements['group'] & {
  animation?: string | null
  fadeDuration?: number
}

export function VaultStairs(props: VaultStairsProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }
  const colors: Record<string, PaletteName> = {
    default: 'default',
    two: 'two',
  }

  return (
    <group {...props} dispose={null}>
      <RigidBody type="dynamic" colliders={false} position={[0, 0, 0.2636]}>
        <ConvexHullCollider args={[nodes['VAULT_STAIRS_colorTwo_dynamic_collider'].geometry.attributes.position.array]} />
        <C4DMesh name={nodes['VAULT_STAIRS_colorTwo_dynamic_collider'].name} geometry={nodes['VAULT_STAIRS_colorTwo_dynamic_collider'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.two} />
        </C4DMesh>
      </RigidBody>
    </group>
  )
}

useGLTF.preload(modelUrl)